# -*- coding: utf-8 -*-
"""Zodiaco.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yv15fdTKnHgLb1KhCe9IUD6SUHryPREs
"""

def signoZ(dia, mes):
    if mes == 1:  # Enero
        if dia >= 21:
            return "Acuario"
        else:
            return "Capricornio"
    elif mes == 2:  # Febrero
        if dia >= 20:
            return "Piscis"
        else:
            return "Acuario"
    elif mes == 3:  # Marzo
        if dia >= 21:
            return "Aries"
        else:
            return "Piscis"
    elif mes == 4:  # Abril
        if dia >= 21:
            return "Tauro"
        else:
            return "Aries"
    elif mes == 5:  # Mayo
        if dia >= 22:
            return "Géminis"
        else:
            return "Tauro"
    elif mes == 6:  # Junio
        if dia >= 22:
            return "Cáncer"
        else:
            return "Géminis"
    elif mes == 7:  # Julio
        if dia >= 23:
            return "Leo"
        else:
            return "Cáncer"
    elif mes == 8:  # Agosto
        if dia >= 24:
            return "Virgo"
        else:
            return "Leo"
    elif mes == 9:  # Septiembre
        if dia >= 23:
            return "Libra"
        else:
            return "Virgo"
    elif mes == 10:  # Octubre
        if dia >= 24:
            return "Escorpio"
        else:
            return "Libra"
    elif mes == 11:  # Noviembre
        if dia >= 23:
            return "Sagitario"
        else:
            return "Escorpio"
    elif mes == 12:  # Diciembre
        if dia >= 22:
            return "Capricornio"
        else:
            return "Sagitario"
    else:
        return "Fecha inválida"

def descripcionZ(dia, mes):
    if mes == 1:  # Enero
        if dia >= 21:
            return "El Sol en Acuario ha sido llamado el «rebelde» del zodíaco debido a su compromiso total con su visión única. Están inflexiblemente anclados en sus propias vidas, y conceden la misma autonomía a los demás. Esto puede hacer que parezcan distantes y amigables al mismo tiempo, con un sentido innato de que cada uno debe «hacer lo suyo»."
        else:
            return "Aquellos con el Sol en Capricornio irradian un sentido de estar a cargo, y usualmente lo están. Pueden estar en busca de estatus y poder, pero nunca comprometen su integridad para llegar allí. Estos son los maestros del reino físico, y ampliamente admirados por lo que son capaces de lograr"
    elif mes == 2:  # Febrero
        if dia >= 20:
            return "Las personas con el Sol en Piscis suelen ser compasivas, románticas y creativas. Tienen una fuerte conexión con el mundo emocional y espiritual, lo que les permite empatizar con los demás y percibir energías sutiles. Además, suelen ser soñadores y estar en sintonía con su intuición, lo que les permite ver más allá de lo evidente."
        else:
            return "El Sol en Acuario ha sido llamado el «rebelde» del zodíaco debido a su compromiso total con su visión única. Están inflexiblemente anclados en sus propias vidas, y conceden la misma autonomía a los demás. Esto puede hacer que parezcan distantes y amigables al mismo tiempo, con un sentido innato de que cada uno debe «hacer lo suyo»."
    elif mes == 3:  # Marzo
        if dia >= 21:
            return "El Sol en Aries conlleva una personalidad fuerte, entusiasta y llena de vitalidad. Los arianos somos conocidos por nuestra valentía, pasión y determinación, y siempre estamos listos para enfrentar cualquier desafío que se nos presente."
        else:
            return "Las personas con el Sol en Piscis suelen ser compasivas, románticas y creativas. Tienen una fuerte conexión con el mundo emocional y espiritual, lo que les permite empatizar con los demás y percibir energías sutiles. Además, suelen ser soñadores y estar en sintonía con su intuición, lo que les permite ver más allá de lo evidente."
    elif mes == 4:  # Abril
        if dia >= 21:
            return "La posición del Sol en Tauro define a las personas nacidas bajo este signo como seres perseverantes, estables, prácticos y amantes del placer y la comodidad. La influencia de Tauro les otorga una gran determinación, paciencia y una fuerte conexión con la naturaleza y los placeres sensoriales. Además, suelen ser personas muy leales, confiables y con un alto sentido del valor y la posesión."
        else:
            return "El Sol en Aries conlleva una personalidad fuerte, entusiasta y llena de vitalidad. Los arianos somos conocidos por nuestra valentía, pasión y determinación, y siempre estamos listos para enfrentar cualquier desafío que se nos presente."
    elif mes == 5:  # Mayo
        if dia >= 22:
            return "El Sol en Géminis me otorga un espíritu curioso, comunicativo y adaptable, lo que me hace disfrutar de la exploración de distintos intereses y la interacción social. Aunque a veces pueda ser difícil concentrarme en una sola cosa por mucho tiempo, también me brinda la capacidad de ver las situaciones desde diferentes perspectivas y de adaptarme a los cambios con facilidad."
        else:
            return "La posición del Sol en Tauro define a las personas nacidas bajo este signo como seres perseverantes, estables, prácticos y amantes del placer y la comodidad. La influencia de Tauro les otorga una gran determinación, paciencia y una fuerte conexión con la naturaleza y los placeres sensoriales. Además, suelen ser personas muy leales, confiables y con un alto sentido del valor y la posesión."
    elif mes == 6:  # Junio
        if dia >= 22:
            return "El Sol en Cáncer confiere a las personas una sensibilidad profunda y una gran capacidad para conectar emocionalmente con los demás. La influencia de este astro en el signo de Cáncer otorga una naturaleza protectora, maternal y muy empática. Las personas con esta posición suelen ser cariñosas, intuitivas, afectuosas y tienen un fuerte sentido de pertenencia a la familia y al hogar. También pueden ser algo susceptibles y emocionales, lo que les lleva a tomar decisiones basadas en sus sentimientos y a ser bastante leales a las personas que aman."
        else:
            return "El Sol en Géminis me otorga un espíritu curioso, comunicativo y adaptable, lo que me hace disfrutar de la exploración de distintos intereses y la interacción social. Aunque a veces pueda ser difícil concentrarme en una sola cosa por mucho tiempo, también me brinda la capacidad de ver las situaciones desde diferentes perspectivas y de adaptarme a los cambios con facilidad."
    elif mes == 7:  # Julio
        if dia >= 23:
            return "El Sol en Leo irradia una energía fuerte, apasionada y llena de vitalidad. Los leoninos suelen ser personas seguras de sí mismas, con una gran autoestima y una necesidad de ser reconocidos y admirados. Son generosos, leales y muy creativos, buscando siempre destacar y brillar en todo lo que hacen. Les encanta ser el centro de atención y suelen tener una personalidad magnética que atrae a los demás."
        else:
            return "El Sol en Cáncer confiere a las personas una sensibilidad profunda y una gran capacidad para conectar emocionalmente con los demás. La influencia de este astro en el signo de Cáncer otorga una naturaleza protectora, maternal y muy empática. Las personas con esta posición suelen ser cariñosas, intuitivas, afectuosas y tienen un fuerte sentido de pertenencia a la familia y al hogar. También pueden ser algo susceptibles y emocionales, lo que les lleva a tomar decisiones basadas en sus sentimientos y a ser bastante leales a las personas que aman."
    elif mes == 8:  # Agosto
        if dia >= 24:
            return "El Sol en Virgo me da una mentalidad práctica, detallista y analítica. Me siento cómodo organizando y optimizando las tareas diarias, buscando siempre la perfección en todo lo que hago. Aunque a veces pueda parecer crítico o demasiado exigente, en realidad tengo una gran preocupación por el bienestar de los demás y una fuerte ética de trabajo que me impulsa a mejorar constantemente."
        else:
            return "El Sol en Leo irradia una energía fuerte, apasionada y llena de vitalidad. Los leoninos suelen ser personas seguras de sí mismas, con una gran autoestima y una necesidad de ser reconocidos y admirados. Son generosos, leales y muy creativos, buscando siempre destacar y brillar en todo lo que hacen. Les encanta ser el centro de atención y suelen tener una personalidad magnética que atrae a los demás."
    elif mes == 9:  # Septiembre
        if dia >= 23:
            return "El Sol en Libra confiere a las personas un sentido innato de equilibrio, armonía y justicia. Los libranos son conocidos por su naturaleza amable, diplomática y socialmente consciente. Tienen una gran capacidad para ver todos los lados de una situación y tienden a valorar las relaciones personales y el trabajo en equipo. Además, suelen ser muy estéticos y les gusta rodearse de belleza y elegancia."
        else:
            return "El Sol en Virgo me da una mentalidad práctica, detallista y analítica. Me siento cómodo organizando y optimizando las tareas diarias, buscando siempre la perfección en todo lo que hago. Aunque a veces pueda parecer crítico o demasiado exigente, en realidad tengo una gran preocupación por el bienestar de los demás y una fuerte ética de trabajo que me impulsa a mejorar constantemente."
    elif mes == 10:  # Octubre
        if dia >= 24:
            return "El Sol en Escorpio me otorga una intensidad emocional y una profunda capacidad de percepción. Los escorpianos son conocidos por ser apasionados, decididos y muy intuitivos. Tienen una gran capacidad para investigar profundamente cualquier asunto y revelar la verdad oculta detrás de las apariencias. Aunque a veces pueda parecer reservado o misterioso, en realidad soy leal y comprometido con las personas y causas que considero importantes."
        else:
            return "El Sol en Libra confiere a las personas un sentido innato de equilibrio, armonía y justicia. Los libranos son conocidos por su naturaleza amable, diplomática y socialmente consciente. Tienen una gran capacidad para ver todos los lados de una situación y tienden a valorar las relaciones personales y el trabajo en equipo. Además, suelen ser muy estéticos y les gusta rodearse de belleza y elegancia."
    elif mes == 11:  # Noviembre
        if dia >= 23:
            return "El Sol en Sagitario me dota de una energía entusiasta, aventurera y expansiva. Los sagitarianos suelen ser optimistas, filosóficos y con una gran sed de conocimiento y experiencias nuevas. Tienen una mente abierta y una capacidad innata para explorar diferentes culturas y puntos de vista. Aunque a veces pueda parecer imprudente o descuidado, en realidad soy un buscador de la verdad y estoy siempre en busca de la sabiduría y el entendimiento."
        else:
            return "El Sol en Escorpio me otorga una intensidad emocional y una profunda capacidad de percepción. Los escorpianos son conocidos por ser apasionados, decididos y muy intuitivos. Tienen una gran capacidad para investigar profundamente cualquier asunto y revelar la verdad oculta detrás de las apariencias. Aunque a veces pueda parecer reservado o misterioso, en realidad soy leal y comprometido con las personas y causas que considero importantes."
    elif mes == 12:  # Diciembre
        if dia >= 22:
            return "El Sol en Capricornio me confiere una naturaleza ambiciosa, determinada y responsable. Los capricornianos suelen ser trabajadores, prudentes y con una gran capacidad para alcanzar sus metas a largo plazo. Tienen una fuerte ética de trabajo y un sentido del deber que les impulsa a esforzarse constantemente por el éxito. Aunque a veces pueda parecer reservado o distante, en realidad soy leal y comprometido con las personas y causas que considero importantes."
        else:
            return "El Sol en Sagitario me dota de una energía entusiasta, aventurera y expansiva. Los sagitarianos suelen ser optimistas, filosóficos y con una gran sed de conocimiento y experiencias nuevas. Tienen una mente abierta y una capacidad innata para explorar diferentes culturas y puntos de vista. Aunque a veces pueda parecer imprudente o descuidado, en realidad soy un buscador de la verdad y estoy siempre en busca de la sabiduría y el entendimiento."
    else:
        return "Fecha inválida"


# Función para imprimir la descripción del signo
def imprimir_descripcion(dia, mes):
    signo = signoZ(dia, mes)
    descripcion = descripcionZ(dia, mes)
    print(f"Tu signo zodiacal es {signo}.")
    print(f"Descripción: {descripcion}\n")


# Bucle principal para ingresar múltiples fechas
while True:
    # Pedir al usuario que ingrese la fecha de nacimiento
    try:
        dia = int(input("Ingresa el día de tu nacimiento (1-31): "))
        mes = int(input("Ingresa el mes de tu nacimiento (1-12): "))
    except ValueError:
        print("Error: Debes ingresar un número válido.")
        continue

    # Validar que la fecha ingresada sea válida
    if (mes < 1 or mes > 12) or (dia < 1 or dia > 31):
        print("Error: Fecha de nacimiento no válida. Inténtalo de nuevo.")
        continue

    # Imprimir el signo zodiacal y su descripción
    imprimir_descripcion(dia, mes)

    # Preguntar al usuario si desea continuar o salir
    respuesta = input("¿Deseas ingresar otra fecha? (sí/no): ").lower()
    if respuesta != "sí" and respuesta != "si":
        break

print("Gracias por usar este programa.")